- .vscode/settings.json
- .vscode/stories.tsx.code-snippets
- .vscode/test.code-snippets
관련 이슈: #
-
<br>
- `.stories.xxx` 와 `test.xxx` 에 대한 스니펫을 추가했습니다.
- 해당 파일에서 `!story`와 `!test`를 작성하여 사용할 수 있습니다.
<br>
> :tada: 프로젝트 코드 스니펫 작성

- package.json
- pnpm-lock.yaml
- src/components/ui/Switch/Switch.stories.tsx
- src/components/ui/Switch/Switch.tsx
- src/components/ui/Switch/index.tsx
관련 이슈: #
-
<br>
- switch 컴포넌트 생
- https://ui.shadcn.com/docs/components/switch
<br>
> :tada: switch 토글 컴포넌트 생성

- package.json
- pnpm-lock.yaml
- src/components/ui/Input/Input.stories.tsx
- src/components/ui/Input/Input.tsx
- src/components/ui/Input/index.tsx
- src/components/ui/Label/Label.stories.tsx
- src/components/ui/Label/Label.tsx
- src/components/ui/Label/index.tsx
관련 이슈: #
- 23
<br>
- Input 컴포넌트 추가
- Label 컴포넌트 추가
- Input 스토리에 Label과 함께 사용하는 예시를 작성했습니다.
<br>
> :tada: Input 및 Label 컴포넌트 작성

- package.json
- pnpm-lock.yaml
- src/components/ui/Dialog/Dialog.stories.tsx
- src/components/ui/Dialog/Dialog.tsx
- src/components/ui/Dialog/index.tsx
- src/styles/colors.ts
관련 이슈: 66
<br>
- 컬러 추가 (dialog-background-color)
- 모달 컴포넌트 추가
- 컴포넌트 이름이 Dialog라 일단 Dialog로 작성했습니다. 의견 주세요
- 백그라운드를 아래 스크린샷과 같이 설정했습니다.
- 사용법: https://ui.shadcn.com/docs/components/dialog
<br>
> :tada: Dialog 컴포넌트 생성

- src/app/(root)/(routes)/(home)/page.tsx
- src/app/(root)/(routes)/test-auth-only/page.tsx
- src/app/(root)/(routes)/test-not-auth-only/page.tsx
- src/app/layout.tsx
- src/lib/msw/initMockApi.ts
- src/lib/msw/mocks/authHandlers.ts
- src/lib/msw/mocks/handlers.ts
- src/middleware.ts
- src/styles/globals.css
- src/utils/getServerCookie.ts
관련 티켓 번호: 81
-
<br>
- `middleware.ts`에서 접근 처리
- msw가 서버에서 validate할 때 인식이 안 되네요... test는 이제 서버에서도 잘 되는데 잘 모르겠습니다...
<br>
> :tada: auth 접근 권한 분리

- .github/DISCUSSION_TEMPLATE/Issue.yml
관련 티켓 번호: 129
-
<br>
- JIRA 이슈 번호 입력
- 현재 상황과 버그 내용(예시)
1. 어디 페이지에 접근해서 ...
2. 어떤 것을 클릭했더니 ...
3. 화면에 ...
4. 이러한 에러가 발생하고 있다.
-  예상 원인
-  버그와 관련된 코드
-  버그와 관련된 Log
- discussion 템플릿은 issue 템플릿과 다르게 yml로 만들어야 된다고 하더라고요! 추가되어야 하는 내용이 있다면 알려주세요
- yml에 들어갈 수 있는 형식
textarea, input, markdown,
<br>
- develop에 머지된 이후에 실제로 적용이 되는지 확인할 수 있는 것 같습니다 🙁
> 📝 discussion 템플릿 작성

- src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
- src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
- src/hooks/useDibs.ts
- src/lib/msw/mocks/itemHandlers.ts
- src/types/index.ts
관련 티켓 번호: 156
-
<br>
- 6번 API 명세서에서 찜 관련된 정보 총 2개를 보내주는 것으로 업데이트 되었습니다
- isMyDib : 내가 찜한 상태인지에 대한 유무 boolean 
- dibsCount: 찜 개수 number
- 총 걸린 시간: 54분
<br>
> :sparkles: 찜 API 업데이트 버전으로 msw 수정

- src/components/ui/Textarea/Textarea.stories.tsx
- src/components/ui/Textarea/Textarea.tsx
- src/components/ui/Textarea/index.tsx
관련 티켓 번호: 140
-
<br>
- text area 컴포넌트 추가
-
<br>
> :tada: textarea 추가

- src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
- src/app/(root)/(routes)/cards/[cardId]/page.tsx
- src/components/domain/card/suggest-card/SuggestCard.tsx
- src/config/appPath.ts
- src/hooks/api/mutations/useSuggestMutation.ts
- src/lib/msw/mocks/suggestionHandlers.ts
- src/services/suggestion/suggestion.ts
- src/types/suggestion.ts
관련 티켓 번호: 235
-
<br>
- 거래 제안하기를 누르면 제안가능한 내 카드들이 안나오는 문제 고쳤습니다.
- 찔러보기를 누르면 제안됨으로 변하는 낙관적 업데이트 제대로 작동 안됐었던 것 고쳤습니다.
- 바뀐 업데이트 명세서대로 useMutation 추가했고 제대로 오퍼하기/찔러보기 되는 것 확인했습니다.
- 이 부분은 실제 api와 연결만 남은 것 같아요.
- 상세정보 페이지에서 수정하기 클릭시 modify 페이지로 이동 추가
- 내 물건이 아니며 예약중, 거래완료 상태일때는 거래 제안하기 버튼 안나타나도록 기능 추가
-
<br>
> :bug: 오퍼하기/찔러보기 요청 관련 에러 해결

- src/app/(root)/(routes)/cards/components/card-list/CardList.tsx
- src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/MyTradeHistoryList.tsx
- src/app/(root)/(routes)/mypage/mycards/components/my-card-list/MyCardList.tsx
- src/app/(root)/(routes)/mypage/mydibs/components/MyDibsList.tsx
- src/app/(root)/(routes)/mypage/suggestions/components/my-suggestion-list/MySuggestionList.tsx
- src/components/domain/card/trade-status-card/TradeStatusCard.tsx
- src/components/domain/exception-boundary/ExceptionBoundary.tsx
- src/components/domain/exception-boundary/index.tsx
- src/components/ui/card/Card.stories.tsx
관련 티켓 번호: 247
- 각 리스트 페이지(카드, 내 카드, 내 제안, 내 거래내역, 내 찜 목록)에 예외처리를 했습니다.
<br>
- ExceptionBoundary라는 상위 컴포넌트로 로딩, 에러, 데이터 없음 등의 케이스에 대한 예외를 처리하였습니다.
- 
<br>
> :tada: 각 리스트 페이지 예외처리

- next.config.js
- package.json
- pnpm-lock.yaml
- src/app/(root)/(routes)/(auth)/login/components/RouteCallback.tsx
- src/app/(root)/(routes)/(home)/components/CategorySection.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
- src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
- src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
- src/app/(root)/(routes)/cards/new/components/Category.tsx
- src/app/(root)/(routes)/cards/new/components/PriceRange.tsx
- src/app/(root)/(routes)/cards/new/components/TradeType.tsx
- src/app/(root)/(routes)/cards/new/hooks/useCardUploadForm.ts
- src/components/domain/image-uploader/ImageUploader.tsx
- src/config/appValidation.ts
- src/constants/card.ts
- src/hooks/useValidate.ts
- src/lib/fetchAPI.ts
- src/lib/msw/mocks/handlers.ts
- src/services/auth/auth.ts
- src/services/images/index.ts
- src/utils/isNotNull.ts
관련 티켓 번호: 145
-
<br>
- fetch API 헤더 제거
- authorization 적용되지 않는 문제 수정
- 카드 업로드 관련 api 에러 수정
-
<br>
> :tada: fetch 변경 및 카드 업로드

- .vscode/settings.json
- package.json
- pnpm-lock.yaml
- src/app/(root)/(routes)/chat/page.tsx
- src/hooks/useFirestoreQuery.ts
- src/lib/firebase/index.ts
관련 티켓 번호: 266
-
<br>
- firebase 연결
- firebase 관련 hook 생성
- firebase 테스트 채팅 페이지 생성
-
<br>
> :tada: firebase 연결

- src/app/(root)/(routes)/chat/components/ChatList.tsx
- src/app/(root)/(routes)/chat/page.tsx
관련 티켓 번호: 271
-
<br>
- 채팅방 레이아웃 조정
- sender 기준 변경(to userId)
-
<br>
> :sparkles: 채팅방 레이아웃 및 타입 조정

- src/app/(root)/(routes)/cards/components/search-input/SearchInput.tsx
관련 티켓 번호: 342
- 카드 검색을 엔터키로 제출 할 수 있도록 했습니다.
<br>
- handleKeyDown 이벤트 생성 및 적용
-
<br>
> :tada: 카드 검색 엔터키로 제출 기능 구현

- src/app/(root)/(routes)/(home)/components/CategorySection.tsx
- src/app/(root)/(routes)/chatrooms/components/chat-room-card/ChatRoomCard.tsx
- src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
- src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
- src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
- src/components/domain/card/trade-status-card/TradeStatusCard.tsx
- src/config/appPath.ts
관련 티켓 번호: 345
-
<br>
- 채팅 버튼 누를시, 채팅방 목록으로 이동하는 기능 구현
- 제안 카드 버튼 누를 시, 카드 상세 페이지로 이동하는 기능 구현
-
<br>
> :tada: 제안 확인 카드 클릭시 상세정보 페이지로 이동하는 기능 구현

- src/contexts/TanstackQueryContext.tsx
관련 티켓 번호: 346
- useQuery 캐싱 기능 전역 설정 적용했습니다.
<br>
- QueryClient에 옵션으로 전역 설정 추가했습니다.
- 아마 쿼리마다 적용하신 분들도 계실텐데, 개별적으로 필요한 캐싱 시간이 필요없다면, 지우셔도 될 것 같습니다. 혹은 캐싱시간 논의해서 정하면 좋을 것 같습니다.
<br>
> :tada: useQuery 캐싱 기능 전역 설정 적용

- src/components/domain/header/components/AvatarWithDropdown.tsx
관련 티켓 번호: 312
-
<br>
- 아바타 클릭 시 나타나는 드롭다운의 위치가 화면 밖으로 나가는 이슈를 해결했습니다.
-
<br>
> :sparkles: 드롭다운 위치 조정

- next.config.js
- src/app/layout.tsx
- tailwind.config.js
관련 티켓 번호: 314
-
<br>
- 다크모드 비활성화 처리
-
<br>
> :sparkles: 다크모드 비활성화

- src/app/(root)/(routes)/cards/[cardId]/components/description-section/DescriptionSection.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/description-section/Dibs.tsx
- src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
- src/app/(root)/(routes)/cards/[cardId]/page.tsx
- src/contexts/TanstackQueryContext.tsx
- src/hooks/api/queries/useCardInfoQuery.ts
관련 티켓 번호: 325, 328
- 버그와 관련된 내용들을 수정했습니다
<br>
- 내 물건은 찜을 하지 못하도록 변경했습니다.
- 로그인을 하지 않은 상태에서도 상세정보 페이지에서 물건정보를 볼 수 있도록 변경하였습니다.
-
<br>
> :bug: 내 물건이 아닐때만 찜 가능하도록 변경 + 로그인X상태에서도 물건 정보 보이게 변경

- src/hooks/useValidate.ts
관련 티켓 번호: 355
-
<br>
- 토큰 만료 시 동작이 없는 부분을 수정했습니다.
- access token 기간 자체가 짧아 refresh token 관련 내용을 백엔드와 함께 추가할 예정입니다.
<br>
> :bug: 토큰 관리 재정의

- src/app/(root)/(routes)/cards/new/hooks/useCardUploadForm.ts
- src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/ChatList.tsx
- src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
- src/app/layout.tsx
- src/components/domain/header/Header.tsx
- src/components/domain/header/components/AvatarWithDropdown.tsx
- src/components/domain/header/components/MenuButton.tsx
관련 티켓 번호: 366
-
<br>
- 업로드 후 게시글로 라우팅
- 채팅 관련 css 수정
- 모바일 뷰포트 설정 추가
- 링크 위치 및 구성 변경
-
<br>
> ✨ 라우터 조건 및 위치 수정

- src/app/(root)/(routes)/(auth)/login/components/RouteCallback.tsx
- src/app/(root)/(routes)/(home)/components/CategorySection.tsx
- src/components/domain/header/sections/RightSide.tsx
- src/hooks/api/queries/useNotificationCountQuery.ts
- src/hooks/useValidate.ts
관련 티켓 번호: 356
<br>
- 알림 방식을 CSR로 변경
- validation 변경사항 적용
- 홈페이지 이미지 서버 컴포넌트로 변경
-
<br>
> :sparkles: 렌더링 및 패치 방식 변경

- src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
- src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
- src/constants/staleTime.ts
관련 티켓 번호: 360
- 
<br>
- 기존에 Select 가 change될 때, 쿼리 스트링이 추가되는 동작이 아닌 버튼을 누를시 쿼리 스트링이 추가되도록 변경하였습니다.
- staleTime 각 리스트에서 제거 했습니다.
-
<br>
> :tada: 검색 필터 모달 UI 및 기능 변경(일괄적용, 일괄 초기화 버튼 생성)

- src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
- src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
- src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
- src/constants/staleTime.ts
- src/hooks/api/mutations/useNotificationUpdateMutation.ts
관련 티켓 번호: 362
-
<br>
- useNotificationUpdateMutation 생성 및 적용
-
<br>
> :tada: 개별 알림 처리 기능 구현

- src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
- src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
- src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
- src/constants/staleTime.ts
- src/hooks/api/mutations/useNotificationUpdateMutation.ts
관련 티켓 번호: 364
-
<br>
- 내 카드(MyCard) 이미지 누를시, 물건 상세 정보 페이지로 이동할 수 있도록 했습니다.
-
<br>
> :tada: 내 카드 이미지 누를시, 물건 상세 정보 페이지로 이동 기능

- package.json
- pnpm-lock.yaml
- src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
- src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
- src/app/(root)/(routes)/cards/my/components/my-card-list-content/MyCardListContent.tsx
- src/app/(root)/(routes)/cards/my/components/my-card-list/MyCardList.tsx
- src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
- src/app/(root)/(routes)/chatrooms/components/chat-room-list-content/ChatRoomListContent.tsx
- src/app/(root)/(routes)/dibs/components/MyDibsTemplate.tsx
- src/app/(root)/(routes)/history/components/my-trade-history-list-content/MyTradeHistoryListContent.tsx
- src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
- src/app/(root)/(routes)/notifications/components/notification-list-content/NotificationListContent.tsx
- src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
- src/components/domain/exception-boundary/ExceptionBoundary.tsx
- src/constants/staleTime.ts
- src/contexts/TanstackQueryContext.tsx
- src/hooks/api/mutations/useNotificationUpdateMutation.ts
- src/hooks/api/queries/useCardsQuery.ts
관련 티켓 번호: 363
-
<br>
- 각 리스트 컴포넌트에 에러바운더리를 적용했습니다.(Suspense는 useInfiniteQuery에서 사용할 수 없다는데 맞나요?)
- 그리고 API에서 발생하는 에러는 에러바운더리가 아니라 isError를 통해서 처리를 해줘야 한다고 하더군요..(이것도 사실인가요?)
-
<br>
> :tada: 각 리스트 컴포넌트 에러바운더리 적용

- src/app/(root)/(routes)/(home)/components/HistorySection.tsx
- src/app/(root)/(routes)/(home)/components/Slider.tsx
- src/app/(root)/(routes)/(home)/page.tsx
- src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
- src/components/ui/card/Card.tsx
- src/components/ui/divider/Divider.tsx
관련 티켓 번호: 357
-
<br>
- 카드 테두리 변경 등
-
<br>
> :sparkles: 마이너 css 변경사항

- next.config.js
- src/app/(root)/(routes)/(home)/components/CategorySection.tsx
- src/app/(root)/(routes)/(home)/components/Slider.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/description-section/Dibs.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/trade-section/PokeUnavailableInfo.tsx
- src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeInfo.tsx
- src/app/(root)/(routes)/cards/[cardId]/page.tsx
- src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
- src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
- src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestCard.tsx
- src/app/(root)/(routes)/chatrooms/components/chat-room-card/ChatRoomCard.tsx
- src/app/(root)/(routes)/history/components/my-trade-history-list/MyTradeHistoryList.tsx
- src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
- src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
- src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
- src/components/domain/card/suggest-card/SuggestCard.tsx
- src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
- src/components/domain/card/trade-status-card/TradeStatusCard.tsx
- src/components/domain/image-uploader/components/ImageBlock.tsx
- src/components/domain/logo/Logo.tsx
- src/components/domain/slider/Slider.tsx
- src/components/ui/card/Card.stories.tsx
- src/components/ui/card/Card.tsx
- src/config/imageLoader.ts
- src/hooks/api/mutations/useNotificationUpdateMutation.ts
- src/hooks/useValidate.ts
관련 티켓 번호: 361
-
<br>
- 이미지 사이즈 최적화
- 나비장터의 컨텐츠 크기에 맞게 불러오는 이미지 사이즈 한정
- 버전에 맞는 이미지 props로 변경
<br>
> :sparkles: 이미지 사이즈 최적화

- README.md
> :tada: 리드미 작성

- src/app/robots.ts
- src/app/sitemap.ts
- src/types/metadata-interface.d.ts
관련 티켓 번호: 377
-
<br>
- sitemap과 robots 설정 추가
-
<br>
> :tada: sitemap 및 robots 추가

- src/app/(root)/(routes)/cards/[cardId]/modify/loading.tsx
- src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
- src/app/(root)/(routes)/cards/my/components/my-card-list-content/MyCardListContent.tsx
- src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/ChatList.tsx
- src/app/(root)/(routes)/mypage/loading.tsx
- src/app/(root)/(routes)/notifications/components/notification-list-content/NotificationListContent.tsx
- src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
- src/app/@authModal/(...)login/loading.tsx
- src/app/loading.tsx
- src/app/robots.ts
- src/app/sitemap.ts
- src/components/domain/header/components/AvatarWithDropdown.tsx
- src/components/domain/header/sections/RightSide.tsx
- src/components/domain/infinite-scroll-loading/InfiniteScrollLoading.tsx
- src/components/domain/infinite-scroll-loading/index.tsx
- src/types/declaration.d.ts
- src/types/metadata-interface.d.ts
---------
관련 티켓 번호: 
-
<br>
-
-
<br>
> :truck: merge develop

- src/lib/fetchAPI.test.ts
- src/utils/getQueryParams.test.ts
- src/utils/getServerCookie.test.ts
- src/utils/getValueByKey.test.ts
- src/utils/isNotNull.test.ts
- tsconfig.json
- vitest.config.js
관련 티켓 번호: 384
-
<br>
- 유틸리티 메서드 및 모듈에 대한 테스트 작성
- 테스트 세팅
-
<br>
> 🧪 테스트 코드 작성
